### ISSUE TITLE
add Gitea support

### ISSUE THREAD

**Issue by timroster** [IBM/automation-integration-platform#12]
Current README steps require providing an external git repo and token to configure for ArgoCD.

Would be great to have Gitea support in this public version. Looks like there's a reference to the gitea in the ODF BOM, but by then it is too late, needs to be handled in the 200 layer.

**Comment by gowdhaman-j** [comment]
200.xx module is from core & common framework. Waiting for 200-xxx to be updated. Post that CP4I related BOM will be updated with Gitea support.

**Comment by gowdhaman-j** [comment]
Add the Gitea Support for the BOM.
