### ISSUE TITLE
launch.sh fails to start container image

### ISSUE THREAD

**Issue by timroster** [IBM/automation-integration-platform#18]
after #14 when running on (MacOS/podman, CentOS/docker) the container launch fails with errors like:

```
invalid argument "=" for "-e, --env" flag: invalid environment variable: =
```

Appears that the logic to convert `export` statements to keys and tokens in the script is incorrectly passing along blank lines in the `credentials.properties` file.

**Comment by timroster** [comment]
known issue: https://github.com/cloud-native-toolkit/automation-solutions/issues/198

**Comment by timroster** [comment]
fixed in upstream with https://github.com/cloud-native-toolkit/automation-solutions/pull/206

**Comment by gowdhaman-j** [comment]
Updated launch.sh and published
