### ISSUE TITLE
Not in sync with automation solutions

### ISSUE THREAD

**Issue by triceam** [IBM/automation-integration-platform#23]
The latest launch script in this repo is not in sync with the latest in automation solutions.  We need to make sure to regenerate so it pulls in the latest launch script, which references the latest images, and will also pull in the latest module versions.

See: https://github.com/cloud-native-toolkit/automation-solutions/blob/main/common-files/launch.sh

**Comment by gowdhaman-j** [comment]
Currently we are working on testing the integration-automation solutions asset on AWS & Azure. We have taken the latest launch.sh, Readme.md etc. Once we finish our testing we shall check-in the asset.

**Comment by gowdhaman-j** [comment]
Tested on AWS & Azure with the latest launch.sh
